apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: db-pvc
    labels:
        app: nextcloud
        volume: db
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 8Gi
    storageClassName: ""
    selector:
        matchLabels:
            app: nextcloud
            volume: db