apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  # labels:
  # app: nextcloud
  # volume: db
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
    # selector:
    #     matchLabels:
    #         app: nextcloud
    #         volume: db
