---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret
type: generic
data:
  key: AQCtFpBggnUTLxAAlQeUelD0/u1lwpHscCmCQA==
---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret-kube
type: generic
data:
  key: AQAZwZJgGoM6KxAAct1tAtsnF+JZ4Eg/t8CEoA==
