---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wiki-postgresql
spec:
  storageClassName: manual
  volumeName: cephfs-vol7
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
