---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-nextcloud
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-rbd-sc
