apiVersion: v1
kind: PersistentVolume
metadata:
    name: nextcloud-data
    labels:
        volume: nextcloud-data
spec:
    accessModes:
        - ReadWriteOnce
    capacity:
        storage: 8Gi
    nfs:
        server: 10.138.0.28
        path: "/share/nextcloud"
        readOnly: false