apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: redis-claim0-pv
  name: redis-claim0-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
      storage: 10Gi
  nfs:
    server: 10.233.92.42
    # server: cloud74
    path: "/share/redis-claim0-pv"
    readOnly: false