---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cephfs-vol2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  cephfs:
      monitors:
      - 192.168.112.106:6789
      - 192.168.112.106:6789
      path: /vol2
      user: admin
      secretRef:
        name: ceph-secret-admin
        namespace: default
