apiVersion: v1
kind: Service
metadata:
  name: {{ include "peertube.fullname" . }}
  labels:
    {{- include "peertube.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      # targetPort: http
      nodePort: 30001
      protocol: TCP
      name: http
  selector:
    {{- include "peertube.selectorLabels" . | nindent 4 }}
