{{- if .Values.hpa.enabled -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "wiki.fullname" . }}
  labels:
    {{- include "wiki.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: {{ template "wiki.fullname" . }}
  minReplicas: {{ .Values.hpa.minPods }}
  maxReplicas: {{ .Values.hpa.maxPods }}
  targetCPUUtilizationPercentage: {{ .Values.hpa.cputhreshold }}
{{- end }}