apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: webserver
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webserver
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/: "true"
        io.kompose.service: webserver
    spec:
      containers:
        - env:
            - name: OPENDKIM_DOMAINS
              valueFrom:
                configMapKeyRef:
                  key: OPENDKIM_DOMAINS
                  name: env
            - name: OPENDKIM_RequireSafeKeys
              valueFrom:
                configMapKeyRef:
                  key: OPENDKIM_RequireSafeKeys
                  name: env
            - name: PEERTUBE_ADMIN_EMAIL
              valueFrom:
                configMapKeyRef:
                  key: PEERTUBE_ADMIN_EMAIL
                  name: env
            - name: PEERTUBE_DB_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: PEERTUBE_DB_HOSTNAME
                  name: env
            - name: PEERTUBE_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: PEERTUBE_DB_PASSWORD
                  name: env
            - name: PEERTUBE_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: PEERTUBE_DB_USERNAME
                  name: env
            - name: PEERTUBE_SMTP_DISABLE_STARTTLS
              valueFrom:
                configMapKeyRef:
                  key: PEERTUBE_SMTP_DISABLE_STARTTLS
                  name: env
            - name: PEERTUBE_SMTP_FROM
              valueFrom:
                configMapKeyRef:
                  key: PEERTUBE_SMTP_FROM
                  name: env
            - name: PEERTUBE_SMTP_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: PEERTUBE_SMTP_HOSTNAME
                  name: env
            - name: PEERTUBE_SMTP_PORT
              valueFrom:
                configMapKeyRef:
                  key: PEERTUBE_SMTP_PORT
                  name: env
            - name: PEERTUBE_SMTP_TLS
              valueFrom:
                configMapKeyRef:
                  key: PEERTUBE_SMTP_TLS
                  name: env
            - name: PEERTUBE_TRUST_PROXY
              valueFrom:
                configMapKeyRef:
                  key: PEERTUBE_TRUST_PROXY
                  name: env
            - name: PEERTUBE_WEBSERVER_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: PEERTUBE_WEBSERVER_HOSTNAME
                  name: env
            - name: POSTFIX_myhostname
              valueFrom:
                configMapKeyRef:
                  key: POSTFIX_myhostname
                  name: env
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: env
          image: chocobozzz/peertube-webserver:latest
          name: webserver
          ports:
            - containerPort: 80
            - containerPort: 443
          resources: {}
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/peertube.template
              name: webserver-claim0
            - mountPath: /var/www/peertube/peertube-latest/client/dist
              name: assets
              readOnly: true
            - mountPath: /var/www/peertube/storage
              name: webserver-claim2
            - mountPath: /var/www/certbot
              name: certbot-www
            - mountPath: /etc/letsencrypt
              name: webserver-claim4
      restartPolicy: Always
      volumes:
        - name: webserver-claim0
          persistentVolumeClaim:
            claimName: webserver-claim0
        - name: assets
          persistentVolumeClaim:
            claimName: assets
            readOnly: true
        - name: webserver-claim2
          persistentVolumeClaim:
            claimName: webserver-claim2
        - name: certbot-www
          persistentVolumeClaim:
            claimName: certbot-www
        - name: webserver-claim4
          persistentVolumeClaim:
            claimName: webserver-claim4
status: {}
