---
apiVersion: v1
kind: ConfigMap
data:
  config.json: |-
    [
      {
        "clusterID": "23fec7b2-ac24-11eb-8d6b-25a16fcaf61d",
        "monitors": [
          "192.168.112.106:6789",
          "192.168.112.107:6789"
        ]
      }
    ]
metadata:
  name: ceph-csi-config
